// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var aws, aws_conf, conf;

  conf = require('./config');

  aws_conf = conf.AWS;

  aws = {};

  aws.ec2 = require('aws-sdk').ec2({
    accessKeyId: aws_conf.ACCESS_KEY,
    secretAccessKey: aws_conf.SECRET_KEY,
    sslEnabled: true
  });

  aws.create_instances = function(InstanceType, KeyName, PrivateIpAddress, SubnetId) {
    var params;
    return params = {
      ImageId: aws_conf.IMAGEID,
      MaxCount: 1,
      MinCount: 1,
      InstanceType: InstanceType || aws_conf.INSTANCETYPE,
      KeyName: KeyName || aws_conf.KEYNAME,
      SubnetId: SubnetId || aws_conf.SUBNETID
    };
  };

  module.exports = aws;

}).call(this);
